--1. LIET KE DANH SACH NHAN VIEN
SELECT *
FROM NHANVIEN
--2. LIET KE DANH SACH CAC DE AN
SELECT *
FROM DEAN
--3. HO TEN NHAN VIEN NU PHONG SO 4
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE PHG = 4 AND PHAI = N'Nữ'
--4. HO TEN NHAN VIEN CO MA 009
SELECT MANV, HONV,TENLOT, TENNV
FROM NHANVIEN
WHERE MANV = 009
--5. HO TEN NHAN VIEN CO DIA CHI O TPHCM, SAP THEO NGAY SINH TANG DAN
SELECT MANV, HONV, TENLOT, TENNV, NGSINH
FROM NHANVIEN
WHERE DCHI LIKE '%TP HCM%'
ORDER BY NGSINH
--6. HO NHAN VIEN CO TEN KET THUC BANG CHU N, SAP KET QUA THEO MA NHAN VIEN GIAM DAN
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE '%N'
ORDER BY MANV DESC
--7. NHAN VIEN CO TEN MA KY TU THU 2 LA TU A DEN D
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE '_[a-d]%'
--8. NHAN VIEN CO TEN MA KY TU THU 2 KHONG PHAI TU A DEN D
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE '_[^a-d]%'
--9. HO TEN NHAN VIEN SINH TU THANG 1 DEN THANG 3
SELECT HONV, TENLOT, TENNV, NGSINH
FROM NHANVIEN
WHERE MONTH(NGSINH) BETWEEN 1 AND 3
--10. HO TEN NHAN VIEN CO LUONG TU 30000 DEN 40000, SAP THEO TEN, TEN LOT VA HO TANG DAN
SELECT HONV, TENLOT, TENNV, LUONG
FROM NHANVIEN
WHERE LUONG BETWEEN 30000 AND 40000
ORDER BY TENNV, TENLOT, HONV
--11. NHAN VIEN LAM TRUONG PHONG, THONG TIN GOM HO TEN PHONG VA TEN PHONG, SAP THEO NGAY NHAN CHUC GIAM DAN
SELECT MANV, HONV, TENLOT, TENNV, TRPHG, NG_NHANCHUC
FROM NHANVIEN, PHONGBAN
WHERE MANV = TRPHG
ORDER BY NG_NHANCHUC DESC
--12. LAM GIONG CAU TREN SU DUNG PHEP KET TRAI VOI BANG BEN TRAI LA NHAN VIEN, NHAN XET VA SO SANH KET QUA
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN LEFT JOIN PHONGBAN ON PHG = MAPHG
WHERE MANV = TRPHG
ORDER BY NG_NHANCHUC DESC

--12.THEM- CHO BIET THONG TIN NHAN VIEN CO HO TEN VA CHU CAI THU 3 LA U VA TEN BAT DAU TU A-P
SELECT *
FROM NHANVIEN
WHERE HONV LIKE '__u%' and  TENNV LIKE '[A-P]%'
--13.THEM- CHO BIET HO TEN TAT CA NHAN VIEN VA HO TEN NGUOI QUAN LY CUA NHAN VIEN
SELECT NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV + ' ' AS HOTENNV, QL.HONV + ' ' + QL.TENLOT + ' ' + QL.TENNV AS HOTENQL
FROM NHANVIEN NV LEFT JOIN NHANVIEN QL ON NV.MA_NQL = QL.MANV
--14.THEM- CHO BIET THONG TIN PHONG BAN VA SO LUONG DE AN PHONG BAN DO QUAN LY
SELECT TENPHG, MAPHG, COUNT(MADA) SOLUONGDEAN
FROM PHONGBAN, DEAN
WHERE MAPHG = PHONG
GROUP BY TENPHG, MAPHG

SELECT TENPHG, MAPHG, COUNT(MADA) SOLUONGDEAN
FROM PHONGBAN LEFT JOIN DEAN ON MAPHG = PHONG
GROUP BY TENPHG, MAPHG
--15.THEM- CHO BIET TEN PHONG BAN, SO LUONG NHAN VIEN, SO LUONG NHAN VIEN NAM, SO LUONG NHAN VIEN NU
SELECT TENPHG, COUNT(*) SLNV
	SUM(CASE WHEN PHAI = 'NAM' THEN 1 ELSE 0 END) SLNAM
FROM PHONGBAN, NHANVIEN
WHERE MAPHG = PHG
GROUP BY MAPHG, TENPHG

SELECT TENPHG, COUNT(MANV) SLNV
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY TENPHG
SELECT TENPHG, COUNT(MANV) SLNAM
FROM NHANVIEN, PHONGBAN
WHERE PHAI = 'Nam' AND PHG = MAPHG
GROUP BY TENPHG
SELECT TENPHG, COUNT(MANV) SLNU
FROM NHANVIEN, PHONGBAN
WHERE PHAI = N'Nữ' AND PHG = MAPHG
GROUP BY TENPHG
--13. HO TEN NHAN VIEN VA TEN THAN NHAN, SAP THEO NGAY SINH THAN NHAN TANG DAN
SELECT HONV, TENLOT, TENNV,TENTN,THANNHAN.NGSINH
FROM NHANVIEN, THANNHAN
WHERE MANV = MA_NVIEN
ORDER BY THANNHAN.NGSINH
--14 LAM GIONG CAU TREN VA SU DUNG PHEP KET TRAI VOI BANG BEN TRAI LA NHAN VIEN, NHAN XET VA SO SANH KET QUA
SELECT HONV, TENLOT, TENNV,TENTN,THANNHAN.NGSINH
FROM NHANVIEN LEFT JOIN THANNHAN ON MANV = MA_NVIEN
ORDER BY THANNHAN.NGSINH
--15. LUONG CAO NHAT
SELECT MAX(LUONG) LUONG
FROM NHANVIEN
--16. NHAN VIEN CO LUONG CAO NHAT
SELECT *
FROM NHANVIEN
WHERE LUONG >= ALL (SELECT LUONG
					FROM NHANVIEN)
--17. LUONG THAP NHAT
SELECT MIN(LUONG) LUONG
FROM NHANVIEN
--18. NHAN VIEN CO LUONG THAP NHAT
SELECT *
FROM NHANVIEN
WHERE LUONG <= ALL (SELECT LUONG
					FROM NHANVIEN)
--19. LUONG TRUNG BINH
SELECT AVG(LUONG) LUONG
FROM NHANVIEN
--20. NHAN VIEN CO LUONG THAP HON LUONG TRUNG BINH
SELECT *
FROM NHANVIEN
WHERE LUONG < (SELECT AVG(LUONG)
				FROM NHANVIEN)
--21. CHO BIET 3 NHAN VIEN CO LUONG CAO NHAT
SELECT TOP 3 MANV, TENLOT, TENNV, LUONG
FROM NHANVIEN
ORDER BY LUONG DESC
--21. CHO BIET 3 NHAN VIEN CO LUONG THAP NHAT
SELECT TOP 3 MANV, TENLOT, TENNV, LUONG
FROM NHANVIEN
ORDER BY LUONG 