--1
create proc sp_ngsinh
as
begin
		SELECT*
		FROM NHANVIEN
		ORDER BY NGSINH
end
EXEC sp_ngsinh
--2
CREATE PROC SP_TUOIVEHUU
AS
BEGIN
	SELECT*
	FROM NHANVIEN
	WHERE PHAI=N'NAM' AND YEAR(GETDATE())-YEAR(NGSINH)>=60 OR PHAI=N'Nữ' and YEAR(GETDATE())-YEAR(NGSINH)>=55
END
EXEC SP_TUOIVEHUU
--3
CREATE PROC SP_TANGLUONG_PHONG_NGHIENCUU
AS
BEGIN
UPDATE NHANVIEN
SET LUONG=LUONG*1.1
FROM NHANVIEN JOIN PHONGBAN ON PHG=MAPHG
WHERE TENPHG=N'NGHIÊN CỨU'
END
EXEC SP_TANGLUONG_PHONG_NGHIENCUU
--4
CREATE PROC SP_TANG_TGLAMVIEC
AS
BEGIN
UPDATE PHANCONG
SET THOIGIAN=THOIGIAN+1
WHERE MA_NVIEN='001' AND MADA=20 AND STT=1
END
EXEC SP_TANG_TGLAMVIEC
--5
CREATE PROC SP_XOADA20_PHANCONG
AS
BEGIN
DELETE PHANCONG
WHERE MADA=20
END
EXEC SP_XOADA20_PHANCONG
--6
CREATE PROC SP_XOADA20_DA
AS
BEGIN
DELETE CONGVIEC
WHERE MADA=20
DELETE DEAN
WHERE MADA=20
END
EXEC SP_XOADA20_DA
--7
CREATE PROC SP_THEM_PHANCONG
AS
BEGIN
		
		insert into PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN)
		values ('003',2,2,20)
		
END
exec SP_THEM_PHANCONG
--8
CREATE PROC SP_THEM_NHANVIEN
AS
BEGIN
	INSERT INTO NHANVIEN
	VALUES('NGUYEN','NGOC','THONG','033',NULL,NULL,'NAM',10000000,'003',5)
END
EXEC SP_THEM_NHANVIEN
--THU TUC CO THAM SO DAU VAO
--9
CREATE PROC SP_TUOI_NHANVIEN (@TUOI INT)
AS
BEGIN
	SELECT*
	FROM NHANVIEN
	WHERE YEAR(GETDATE())-YEAR(NGSINH)>=@TUOI
	ORDER BY NGSINH
END
EXEC SP_TUOI_NHANVIEN'60'
--10
CREATE PROC SP_TUOIVEHUU_NHANVIEN( @TUOINAM INT,@TUOINU INT)
AS
BEGIN
	SELECT*
	FROM NHANVIEN
	WHERE PHAI=N'NAM' AND YEAR(GETDATE())-YEAR(NGSINH)>=@TUOINAM OR PHAI=N'Nữ' and YEAR(GETDATE())-YEAR(NGSINH)>=@TUOINU
END
EXEC SP_TUOIVEHUU_NHANVIEN'258','555'
--11

CREATE PROC SP_TANGLUONG_NV(@TENPHONG NVARCHAR(15))
AS
BEGIN
	UPDATE NHANVIEN
	SET LUONG=LUONG*1.1
	FROM PHONGBAN
	WHERE TENPHG=@TENPHONG
END
EXEC SP_TANGLUONG_NV N'NGHIÊN CỨU'
--12
CREATE PROC SP_TANGTG(@MANV CHAR(9),@MADA INT,@STT INT)
AS
BEGIN
	UPDATE PHANCONG
	SET THOIGIAN=THOIGIAN+1
	WHERE MA_NVIEN=@MANV AND MADA=@MADA AND STT=@STT
END
EXEC SP_TANGTG'001','30','1'
--13
CREATE PROC SP_XOA_PHANCONG(@MADA INT)
AS
BEGIN
	DELETE FROM PHANCONG
	WHERE MADA=@MADA
END
EXEC SP_XOA_PHANCONG'30'
--14
CREATE PROC SP_XOA_DA(@MADA INT)
AS
BEGIN
	DELETE FROM CONGVIEC
	WHERE MADA=@MADA
	DELETE FROM DEAN
	WHERE MADA=@MADA
END
EXEC SP_XOA_DA 30
--15
CREATE PROC SP_PHANCONG_INSERT(@MANV CHAR(9),@MADA INT, @STT INT, @THOIGIAN FLOAT)
AS
BEGIN
	INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN)
	VALUES (@MANV,@MADA,@STT,@THOIGIAN)
END
EXEC SP_PHANCONG_INSERT '005',2,2,20
--16
CREATE PROC SP_NHANVIEN_INSERT(@HO NVARCHAR(15),
@TENLOT NVARCHAR(15),
@TENNV NVARCHAR(15),
@MANV CHAR(9),
@NGSINH DATE,
@DCHI NVARCHAR(30),
@PHAI NVARCHAR(3),
@LUONG FLOAT,
@MA_NQL CHAR(9),
@PHG INT
)
AS
BEGIN
	INSERT INTO NHANVIEN
	VALUES (@HO,@TENLOT,@TENNV,@MANV,@NGSINH,@DCHI,@PHAI,@LUONG,@MA_NQL,@PHG)
END
EXEC SP_NHANVIEN_INSERT 'NGUYEN','NGOC','THONGDZ','888','2003-06-18','THUONG DINH XA HOI',N'NAM',10000000000,'005',5