--Khoá chính
ALTER TABLE DEAN
ALTER COLUMN MADA INT NOT NULL
ALTER TABLE DEAN
ADD CONSTRAINT PK_DEAN
PRIMARY KEY (MADA)

ALTER TABLE PHONGBAN
ALTER COLUMN MAPHG INT NOT NULL
ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PHONGBAN
PRIMARY KEY (MAPHG)

ALTER TABLE NHANVIEN
ALTER COLUMN MANV CHAR(9) NOT NULL
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN
PRIMARY KEY (MANV)

ALTER TABLE DIADIEM_PHG
ALTER COLUMN MAPHG INT NOT NULL
ALTER TABLE DIADIEM_PHG
ALTER COLUMN DIADIEM NVARCHAR(15) NOT NULL
ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT PK_DIADIEM_PHG
PRIMARY KEY (MAPHG,DIADIEM)

ALTER TABLE CONGVIEC
ALTER COLUMN MADA INT NOT NULL
ALTER TABLE CONGVIEC
ALTER COLUMN STT INT NOT NULL

ALTER TABLE CONGVIEC
ADD CONSTRAINT PK_CONGVIEC
PRIMARY KEY (MADA,STT)

ALTER TABLE PHANCONG
ALTER COLUMN MA_NVIEN CHAR(9) NOT NULL
ALTER TABLE PHANCONG
ALTER COLUMN MADA INT NOT NULL
ALTER TABLE PHANCONG
ALTER COLUMN STT INT NOT NULL

ALTER TABLE PHANCONG
ADD CONSTRAINT PK_PHANCONG
PRIMARY KEY (MA_NVIEN,MADA,STT)

ALTER TABLE THANNHAN
ALTER COLUMN MA_NVIEN CHAR(9) NOT NULL
ALTER TABLE THANNHAN
ALTER COLUMN TENTN NVARCHAR(15) NOT NULL

ALTER TABLE THANNHAN
ADD CONSTRAINT PK_THANNHAN
PRIMARY KEY (MA_NVIEN,TENTN)

--KHOÁ NGOẠI
ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN
FOREIGN KEY (MA_NVIEN) 
REFERENCES NHANVIEN(MANV)

ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PB
FOREIGN KEY (PHONG)
REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NV
FOREIGN KEY(TRPHG)
REFERENCES NHANVIEN(MANV)

ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT FK_DIADIEMPHG
FOREIGN KEY (MAPHG)
REFERENCES PHONGBAN(MAPHG)

ALTER TABLE CONGVIEC
ADD CONSTRAINT FK_CONGVIEC_DA
FOREIGN KEY (MADA)
REFERENCES DEAN(MADA)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_CV
FOREIGN KEY(MADA,STT)
REFERENCES CONGVIEC(MADA,STT)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NV
FOREIGN KEY(MA_NVIEN)
REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NV
FOREIGN KEY(MA_NQL)
REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONG
FOREIGN KEY(PHG)
REFERENCES PHONGBAN(MAPHG)

