--4A.
i
INSERT INTO NHANVIEN
VALUES (N'Nguyễn', N'Thanh', N'Trúc', '004', '1/1/2000', N'200 Cống Quỳnh Q1 TP HCM',N'nữ', 10000, null, null)
ii
INSERT INTO NHANVIEN
VALUES (N'Nguyễn', N'Thị', N'Loan', '004', '2/2/2000', N'200 Thành Thái Q10 TP HCM',N'nữ', 10000, null, null)
iii
INSERT INTO NHANVIEN
VALUES (N'Nguyễn', N'Thị', N'Loan', '005', '2/2/2000', N'200 Thành Thái Q10 TP HCM',N'nữ', 10000, null, null)

--4B.
i
INSERT INTO NHANVIEN
VALUES (N'Nguyễn', null, N'Lý', '006', '3/3/2000', N'2 Nguyễn Tri Phương Q5 TP HCM',N'nam', 10000, null, 1)
ii
INSERT INTO NHANVIEN
VALUES (N'Nguyễn', null, N'Lý', '006', '3/3/2000', N'2 Nguyễn Tri Phương Q5 TP HCM',N'nam', 10000, null, null)

--5
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NV CHECK (PHAI = 'Nam' or PHAI = N'Nữ')

--6
INSERT INTO DEAN
VALUES (N'Học HQT',1,N'Hà Nội',null)

ALTER TABLE DEAN
ADD CONSTRAINT U_TENDA
UNIQUE (TENDA)

INSERT INTO DEAN
VALUES (N'Học HQT',2,N'Hải Phòng',null)

--7.
ALTER TABLE NHANVIEN
ADD NGAYVAOLAM DATE

ALTER TABLE NHANVIEN
ADD CONSTRAINT DK_NVL
DEFAULT GETDATE() FOR NGAYVAOLAM

INSERT INTO NHANVIEN
VALUES (N'Lê', N'Nguyễn Hoàng', N'Thông', '006', '1/1/2000', N'200 Cống Quỳnh Q1 TP HCM',N'nữ', 10000, null, null, null)

INSERT INTO NHANVIEN
VALUES (N'Lê', N'Nguyễn Hoàng', N'Thông', '007', '1/1/2000', N'200 Cống Quỳnh Q1 TP HCM',N'nữ', 10000, null, null, '27/9/2023')

--8. 
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NGSINH
CHECK (NGAYVAOLAM IS NOT NULL AND NGSINH<NGAYVAOLAM)

--9.
CREATE RULE MAPHG
AS @MAPHG > 0

EXEC sp_bindrule 'MAPHG', 'PHONGBAN.MAPHG'

--10.
CREATE RULE TUOITU18
AS YEAR(GETDATE()-@NGAY) -1900 >=18
EXEC sp_bindrule 'TUOITU18', 'NHANVIEN.NGSINH'

--11.
EXEC sp_unbindrule 'PHONGBAN.MAPHG'

--12.
DROP RULE MAPHG

--13.
ALTER TABLE NHANVIEN
NOCHECK CONSTRAINT CK_NGSINH

--14.
ALTER TABLE NHANVIEN
DROP CONSTRAINT CK_NGSINH

--15.
ALTER TABLE NHANVIEN
NOCHECK CONSTRAINT FK_NHANVIEN_NV
ALTER TABLE NHANVIEN
NOCHECK CONSTRAINT FK_NHANVIEN_PHONG

--16
ALTER TABLE NHANVIEN
CHECK CONSTRAINT FK_NHANVIEN_NV
ALTER TABLE NHANVIEN
CHECK CONSTRAINT FK_NHANVIEN_PHONG

--17
ALTER TABLE NHANVIEN
NOCHECK CONSTRAINT PK_NHANVIEN