--18
CREATE DATABASE QuanLyBanHang
CREATE TABLE KHACHHANG
(
	MAKH NVARCHAR (5),
	TENKH NVARCHAR (30) NOT NULL,
	DIACHI NVARCHAR (50),
	DT NVARCHAR (15),
	EMAIL NVARCHAR (30)
)
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_DT
CHECK (DT >= 8)

CREATE TABLE VATTU
(
	MAVT NVARCHAR (5),
	TENVT NVARCHAR (30) NOT NULL,
	DVT NVARCHAR (20),
	GIAMUA INT,
	SLTON INT
)

ALTER TABLE VATTU
ADD CONSTRAINT CK_GIAMUA
CHECK (GIAMUA>0)

ALTER TABLE VATTU
ADD CONSTRAINT CK_SLTON
CHECK (SLTON >= 0)

ALTER TABLE VATTU
ALTER COLUMN MAVT NVARCHAR(5) NOT NULL
ALTER TABLE VATTU
ADD CONSTRAINT PK_MAVT
PRIMARY KEY(MAVT)

CREATE TABLE HOADON
(
	MAHD NVARCHAR (10),
	NGAY DATE,
	MAKH NVARCHAR (5),
	TONGTG INT
)
ALTER TABLE HOADON
ADD CONSTRAINT CK_NGAY
CHECK (NGAY < GETDATE())

ALTER TABLE HOADON
ALTER COLUMN MAHD NVARCHAR(10) NOT NULL

ALTER TABLE HOADON
ADD CONSTRAINT PK_HD
PRIMARY KEY(MAHD)
CREATE TABLE CHITIETHOADON 
(
	MAHD NVARCHAR (10),
	MAVT NVARCHAR (5),
	SL INT,
	KHUYENMAI INT,
	GIABAN INT
)
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT CK_SL
CHECK (SL > 0)

